### ISSUE TITLE
Option to exclude files from ament_auto_lint

### ISSUE THREAD

**Issue by jacobperron** [ament/ament_lint#119]
It would be convenient if there was a way to exclude one or more files from lint checks when invoking `ament_auto_lint`.
This would be useful in circumstances were a package includes third-party source files (e.g. tinydir in ros2/rcl#332). 
Currently, there is no apparent  way to exclude a file other than not running a particular lint check.
Linters could be called separately (ie. not with `ament_auto_lint`), but some would still need to be extended to support file exclusions.

### Implementation considerations

Ideally, we could pass a file exclusion list to `ament_auto_lint` and let it pass the appropriate flags to the linters it invokes, e.g.

    ament_lint_auto_find_test_dependencies(
      EXCLUDE_FILES
        include/foo/bar.h
        src/bar.c
        src/baz.c
    )

Another option could be to support placing a file (e.g. `ament_lint.cfg`) in the root of the repo that allows configuration of the various linters supported by ament_lint.

**Comment by jacobperron** [comment]
cc/ @AAlon

**Comment by emersonknapp** [comment]
I believe this was closed with https://github.com/ament/ament_lint/pull/386

**Comment by methylDragon** [comment]
This issue was also duplicated in https://github.com/ament/ament_lint/issues/343

I think I will close this.

---

To exclude files, simply:
```cmake
    # this must happen before the invocation of ament_package()
    if(BUILD_TESTING)
      find_package(ament_lint_auto REQUIRED)
      set(AMENT_LINT_AUTO_FILE_EXCLUDE /path/to/ignored_file ...)
      ament_lint_auto_find_test_dependencies()
    endif()
```
