### ISSUE TITLE
ament flake8 does not ignore packages with AMENT/COLCON_IGNORE

### ISSUE THREAD

**Issue by jpsamper2009** [ament/ament_lint#149]
Other `ament` linters will automatically filter out files from directories that have an AMENT_IGNORE: e.g.

-  ament_copyright: https://github.com/ament/ament_lint/blob/master/ament_copyright/ament_copyright/crawler.py#L28
- ament_cpplint: https://github.com/ament/ament_lint/blob/master/ament_cpplint/ament_cpplint/main.py#L208
- ament_lint_cmake:  https://github.com/ament/ament_lint/blob/master/ament_lint_cmake/ament_lint_cmake/main.py#L128

Ideally, `ament flake8` would be consistent with this behavior.

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request for this enhancement.
