### ISSUE TITLE
When build with colcon --symlink-install, ament_uncrustify config winds up in build folder

### ISSUE THREAD

**Issue by rotu** [ament/ament_lint#151]
Not sure if this is a bug or not, but when building `colcon build --packages-select ament_uncrustify --merge-install --symlink-install`, `ament_uncrustify` looks for the default config file at:
`/opt/ros/master/build/ament_uncrustify/ament_uncrustify/configuration/ament_code_style.cfg`

I would expect it to look either within the `src` or the `install` directory, not `build`.

**Comment by dirk-thomas** [comment]
`--symlink-install` maps to `setuptools` `develop` for Python packages. In that case the files are not copied - hence they are not in `install`. The file is actually being in `build` (beside also being in `src`) because `colcon` always does an out-of-source builds in order to not pollute the source space with any files.

**Comment by rotu** [comment]
Oh weird. I just assumed it did a `pip3 install --editable /path/to/parent/of/setup_py --build /path/to/build --target /path/to/install`. Why the extra hoops to reinvent what pip3 does? Just to avoid `.egg-info` files?

**Comment by dirk-thomas** [comment]
Dropping random files like `.egg-info` in the source directory doesn't satisfy the desire to perform an out-of-source-build.

Afaik there is no supported way to perform a full out-of-source build with Python `setuptools`. If you happen to know one please share it and I would be happy to use it instead.

I also don't thin `colcon` reinvent anything. It simply invokes `setup.py` with the available commands / arguments provided by `setuptools`.

**Comment by rotu** [comment]
Thanks for the info. I'm still not sure this is the correct place for the file to wind up, but if not, it's not a bug in ament_uncrustify.
