### ISSUE TITLE
Unclear how to use ament_clang_tidy

### ISSUE THREAD

**Issue by mm318** [ament/ament_lint#203]
Reading the [documentation](https://github.com/ament/ament_lint/blob/master/ament_clang_tidy/doc/index.rst), I would assume
```
ament_clang_tidy --fix-errors
```
works like
```
ament_uncrustify --reformat src/
```
as in the source files in my workspace will be fixed in place.

However, I don't see any changes, and I'm not sure if the script errored out somewhere. It looks like it complained a lot about "stddef.h" and "gtest/gtest.h" not found and gave up.

The question is are there any prerequisite steps needed to be done before running `ament_clang_tidy`, like generating a compilation database (a `compile_commands.json` file) with `colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`, since that's how `run-clang-tidy.py` is typically used.

**Comment by JShep1** [comment]
`ament_clang_tidy` is essentially a wrapped call to `clang-tidy` so it may be necessary to create a `compile_commands.json` file in order for extraneous header files to be found and other corrections  to be made (see also [here](https://stackoverflow.com/questions/39455090/clang-tidy-cant-find-my-header-files)).

**Comment by mm318** [comment]
My current understanding is that even if we do have `compile_commands.json` present, `ament_clang_tidy` does not pass the relevant `-p` option to the underlying `clang-tidy`.

@dirk-thomas and @JShep1, I propose we enhance `ament_clang_tidy --fix-errors` to do the following:
1. Run `colcon configure --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` to run the CMake configuration step for generating the relevant `compile_commands.json` file. (If the `configure` verb doesn't exist in `colcon`, we should add it. It will perform a subset of what `build` currently does.)
2. `ament_clang_tidy --fix-errors` will search subdirectories for `compile_commands.json` and make calls to `run-clang-tidy -fix -p <path_to_db>`

**Comment by jacobperron** [comment]
@mm318 I'd discourage using `colcon` as part of any `ament` functionality since `ament` packages should not have to depend or have knowledge of `colcon`. Can the `compile_commands.json` be generated independently for your project? We can likely still improve `ament_clang_tidy` to accept the compilation database file.

**Comment by mm318** [comment]
> @mm318 I'd discourage using `colcon` as part of any `ament` functionality since `ament` packages should not have to depend on or have knowledge of `colcon`.

Okay, that's reasonable.

> We can likely still improve `ament_clang_tidy` to accept the compilation database file.

I already have a script that makes `clang-tidy` use a compilation database file to find lint issues correctly (but it can't fix issues). I can contribute that `ament_clang_tidy`.

**Comment by dirk-thomas** [comment]
@mm318 What is the status of this ticket?

**Comment by mm318** [comment]
The action is on me to produce a pull request. I will try to get that done by the end of next week.

**Comment by mm318** [comment]
The pull request at https://github.com/ament/ament_lint/pull/213 is ready for review, @JShep1, @jacobperron, and @dirk-thomas.

**Comment by ivanpauno** [comment]
Connected PR has been merged, closing
