### ISSUE TITLE
ament_lint_common skipping ament_copyright when no source files

### ISSUE THREAD

**Issue by Blast545** [ament/ament_lint#237]
Found this bug when enabling `ament_lint_common` tests for the `console_bridge_vendor` package [here](https://github.com/ros2/console_bridge_vendor/pull/10).

In the CI results appears the results for the `xmllint`and `lint_cmake` tests. However, the test `ament_copyright` tests are not run. As this test also checks for the `LICENSE` and `CONTRIBUTING.md` files of the package, it should be running.

Running `ament_copyright` directly over the package folder shows the results of the test, so I think the `ament_ lint_common` at some point of the parsing of the required tests, skips this one in the absence of source files.

**Comment by dirk-thomas** [comment]
This is literally the only logic `ament_lint_common` contains to "trigger" other linters: https://github.com/ament/ament_lint/blob/56c86c406abbef8c379262802fd44f9a96d5b97f/ament_lint_common/CMakeLists.txt#L9

All the decision process is encapsulated in the actual linter package: https://github.com/ament/ament_lint/blob/56c86c406abbef8c379262802fd44f9a96d5b97f/ament_cmake_copyright/cmake/ament_cmake_copyright_lint_hook.cmake#L15-L32

**Comment by Blast545** [comment]
Then the issue is in that file `ament_cmake_copyright_lint_hook.cmake`. It shouldn't check for source files before calling `ament_copyright()` because this linter already skips files that are not considered source files and enforces having a `LICENSE` and a `CONTRIBUTING.md` file in the packages.

If you think that argument is valid, I can add a PR removing that check.

**Comment by dirk-thomas** [comment]
Sounds good to me.
