### ISSUE TITLE
ament_cppcheck is failing with a KeyError on rmw_connext_cpp

### ISSUE THREAD

**Issue by tfoote** [ament/ament_lint#24]
The file [exists](https://github.com/ros2/rmw_connext/blob/master/rmw_connext_cpp/src/functions.cpp), The report variable appears to not have been initialized properly. 

[line with error in traceback](https://github.com/ament/ament_lint/blob/master/ament_cppcheck/ament_cppcheck/main.py#L115)

```
Traceback (most recent call last):
  File "/home/rosbuild/ci_scripts/workspace/install/bin/ament_cppcheck", line 9, in <module>
    load_entry_point('ament-cppcheck==0.0.0', 'console_scripts', 'ament_cppcheck')()
  File "/home/rosbuild/ci_scripts/workspace/install/lib/python3.4/site-packages/ament_cppcheck-0.0.0-py3.4.egg/ament_cppcheck/main.py", line 115, in main
KeyError: 'src/functions.cpp'

```

**Comment by wjwwood** [comment]
@dirk-thomas and I were just talking about that. I pointed out to him that it's failing on the farm:

http://ci.ros2.org/job/ros2_batch_ci_linux/6/testReport/rmw_connext_cpp/cppcheck/missing_result/

He said he's going to look into it.

**Comment by dirk-thomas** [comment]
As a follow up the linter indicates a memory leak in rmw_connext_cpp:http://ci.ros2.org/job/ros2_batch_ci_linux/7/testReport/rmw_connext_cpp/cppcheck/error__memleak__src_functions_cpp_954_/

@wjwwood Are you already in the process of refactoring the allocation / deallocation in rmw?

**Comment by wjwwood** [comment]
Yes. I'm almost done with connext dynamic. I'll open some pull request when I finish it. Then I'll do connext and open splice too. I'll make sure to follow up on that warning explicitly.

**Comment by tfoote** [comment]
There's a debugging print in that commit: https://github.com/ament/ament_lint/commit/58515dc94aa7cc0d01866d8ffc5528dd862a06e4#diff-e801a73ffe02dfdbed0c68181d791d5eR121

**Comment by dirk-thomas** [comment]
Thanks for catching that: removed in c4098a86d38e60f5255d2077859b85cc8447f6a3
