### ISSUE TITLE
Harmonization ament_lint_cmake and cpp_lint

### ISSUE THREAD

**Issue by DentOpt** [ament/ament_lint#273]
If I run standard cpp_lint:
`  cpplint file.cpp `
and 
`  ament_lint_cmake file.cpp`
which both should follow the Google C++ Coding style, I get very different style comments. 
Furthermore, when I run 
`colcon test` with 
```
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
```
It is checking with uncrustify which is again following another standard?! 

1. Where does this style difference come from?
2. Is there a way to give a custom coding style sheet to ament_lint_cmake?
3. Is there a config file that I could use for auto-formatting of my code e.g. eclipse?

**Comment by clalancette** [comment]
> It is checking with uncrustify which is again following another standard?!

By default, we use 3 different checkers; cpplint, uncrustify, and cppcheck .  They all cover slightly different things.

> * Where does this style difference come from?

We don't exactly use Google style.  We use Google style with some exceptions.  You can see it here: https://index.ros.org/doc/ros2/Contributing/Code-Style-Language-Versions/#id1

> 
> * Is there a way to give a custom coding style sheet to ament_lint_cmake?
> 
> * Is there a config file that I could use for auto-formatting of my code e.g. eclipse?

I'm not sure on either of these; @dirk-thomas @claireyywang ?

**Comment by dirk-thomas** [comment]
From the three linter packages (`ament_cppcheck`, `ament_cpplint`, `ament_uncrustify`) only the last one has a separate configuration file you could reference directly when invoking the native tool: https://github.com/ament/ament_lint/blob/8bf194aa1ac282db5483dd0d3fefff8f325b0db8/ament_uncrustify/ament_uncrustify/configuration/ament_code_style.cfg

For `ament_cpplint` all configuration is embedded in the command line options in the command line tools (https://github.com/ament/ament_lint/blob/8bf194aa1ac282db5483dd0d3fefff8f325b0db8/ament_cpplint/ament_cpplint/main.py#L97-L120) so there is unfortunately no good way to reuse them in a natively invoked tool.

For `ament_cppcheck` there is not any style-specific configuration. The used options (`--inline-suppr`, `--language=...`) only determine as what language a file is considered as well as that inline suppression are supported. So `cppcheck` should be usable with the same results as how ROS 2 lints sources without custom configuration.

**Comment by clalancette** [comment]
There's not really a bug here, and there has been no response since this was first opened.  I'm going to go ahead and close this out, but feel free to reopen or keep commenting.
