### ISSUE TITLE
ament_cpplint doesn't support EXCLUDE parameter

### ISSUE THREAD

**Issue by Jopand** [ament/ament_lint#295]
https://github.com/ament/ament_lint/blob/418a69c7e0f922adc889ac1bc2a7dcf721bf7060/ament_cmake_cpplint/cmake/ament_cpplint.cmake#L29

According to the highlighted line, it is possible to set an EXCLUDE parameter. However it doesn't seem to be supported, when calling "ament_cpplint --help"

Either the cmake parameter should be removed - or (hopefully) the parameter should be supported in ament_cpplint

**Comment by mm318** [comment]
Looks like it is due to incompletion of https://github.com/ament/ament_lint/pull/238.
