### ISSUE TITLE
[ament_copyright] Add "Propriatery" licence type (let's make ROS more industry-friendly)

### ISSUE THREAD

**Issue by destogl** [ament/ament_lint#297]
## Issue
When developing proprietary ROS2 code, standard ros-tooling/action-ros-lint CI-configuration fails because of missing support for a "Proprietary" license by `ament_copyright`. Although the code is proprietary, it makes sense to check if there are copyright and license statements in all files.

## Current solution
As proposed by @tfoote at [ROS-Answers](https://answers.ros.org/question/343351/whats-the-proper-way-to-use-a-proprietary-software-license-according-to-ament_copyright/?answer=343355#post-id-343355), an entry point could/should be written to a python package adding support for a specific license. Still, in practice, is this solution very inconvenient, providing extensive code copying across the repositories.

## Proposal for a new solution
Why not add a short and general version of a Proprietary license to `ament_copyright`, which could serve many use-cases? I believe this would significantly increase user-experience from industrial-users. I propose a header along these lines:

```
Copyright (c) $YEAR$, $NAME_ON_LICENSE$
All rights reserved.

Proprietary License

Unauthorized copying of this file via any medium is strictly prohibited.
The file is considered confidential.
```

What do you think?

**Comment by clalancette** [comment]
I honestly don't think this is a good idea.  The basic reason is that there are literally thousands of different proprietary licenses out there.  Each one of them has a different set of terms and restrictions, and a "catch-all" license like this will probably be acceptable to a very small number of them.

As mentioned in the ROS answers thread, the right way to do this is to develop a custom entry point for each proprietary license you want to include (and check) in your code.

I'm going to close this issue out, but feel free to keep commenting or reopen if you want to continue the discussion.

**Comment by tfoote** [comment]
+1 for not adding a catchall that is inspecific as it will end up with the copyright info being unusable. If there's a catchall like this it will become a shortcut that makes the tests pass and then just muddies the water on the information and takes away the value of the checks.

The entry point for a specific license shouldn't be hard to implement and will encourage good practices within the corporations too. It might make sense to have a script or template for setting up that new entry point to make it easier for companies to create their own.

**Comment by destogl** [comment]
@clalancette, @tfoote: I understand your reasons. I will then look at adding a template/script to generate entry point for a proprietary license. Thanks for answering.
