### ISSUE TITLE
CMake linter default line length differs depending on invocation

### ISSUE THREAD

**Issue by emersonknapp** [ament/ament_lint#301]
* Using `ament_lint_cmake` entrypoing from shell - defaults to 80 chars from https://github.com/ament/ament_lint/blob/master/ament_lint_cmake/ament_lint_cmake/cmakelint.py#L87
* Using `ament_cmake_lint_cmake` to call `ament_lint_cmake()` from `CMakeLists.txt` -  it defaults to 140 chars because of https://github.com/ament/ament_lint/blob/master/ament_cmake_lint_cmake/cmake/ament_lint_cmake.cmake#L44

This means that, given no external configurations, calling the same tool two ways can have different results. Not sure what the best way to resolve this is - my first thought is to add a `default=140` to the [ArgumentParser](https://github.com/ament/ament_lint/blob/master/ament_lint_cmake/ament_lint_cmake/main.py#L52) - and to _remove_ the [CMake default](https://github.com/ament/ament_lint/blob/master/ament_cmake_lint_cmake/cmake/ament_lint_cmake.cmake#L44) to avoid duplicate information

**Comment by audrow** [comment]
> my first thought is to add a default=140 to the ArgumentParser - and to remove the CMake default to avoid duplicate information

That sounds good to me. If you want to open a PR for this, feel free to @ me as a reviewer.
