### ISSUE TITLE
How can I recursively specfiy test dependencies?

### ISSUE THREAD

**Issue by FabianSchuetze** [ament/ament_lint#305]
I would like to understand how I can specify recursive test dependencies. Suppose I have the following structure:
```shell 
├── dir1
│   ├── package.xml
├── dir2
│   ├── package.xml
├── CONFIG

```
If `dir1` and `dir2` are both packages, and their `package.xml` file contain `<test_depend>ament_lint_auto</test_depend> `, can I specify in a `CONFIG` file (or in any other file) in the root folder what linters are comprised in `ament_lint_auto`? Reading the [documentation](https://github.com/ament/ament_lint/blob/master/ament_lint_auto/doc/index.rst) of `ament_lint_auto` I have the feeling that this is possible, I however do not really understand how to do that. Does somebody have any idea? I am grateful for any hints or suggestions!

**Comment by audrow** [comment]
Hi @FabianSchuetze, I'm not sure of the answer myself, but I think a better place to ask this question is on [ROS Discourse](https://discourse.ros.org/) so the ROS community can help you with your question.

In general, issues are best for feature requests and bugs, so I'm going to close this issue.

**Comment by FabianSchuetze** [comment]
Thanks for your kind and useful comment @audrow  - that helped me very much!
