### ISSUE TITLE
cpplint incorrectly labels C++17 headers as C headers

### ISSUE THREAD

**Issue by jacobperron** [ament/ament_lint#309]
Consider this example:

```c++
// Copyright 2021 Jacob Perron
#include <iostream>
#include <optional>

int main(void)
{
  return 0;
}
```

IIUC, following the [Google C++ guide](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes), it has the correct, alphabetically sorted, list of included C++ headers.

However, ament_cpplint complains that `<optional>` is a C header and should appear *before* `<iostream>`.

I've noticed that the same issue happens for all C++17 headers, e.g. `<filesystem>`. cpplint doesn't seem to be aware of them. Perhaps there is a patch upstream to fix this, but I haven't taken a look.

**Comment by wjwwood** [comment]
This also comes up for `#include <variant>`

**Comment by zflat** [comment]
@jacobperron Try building the latest `cppcheck` release from source (https://github.com/danmar/cppcheck/releases). If the problem persists then a ticket can be opened at https://trac.cppcheck.net/wiki.

**Comment by jacobperron** [comment]
Updating to a different version of cpplint seems to fix this issue. I've opened a PR https://github.com/ament/ament_lint/pull/324 proposing we switch to tracking this fork: https://github.com/cpplint/cpplint
