### ISSUE TITLE
reenable runtime/int for cpplint

### ISSUE THREAD

**Issue by dirk-thomas** [ament/ament_lint#34]
Related to #33.

Existing code need to be updated to pass.

**Comment by esteve** [comment]
CI Linux job:

http://ci.ros2.org/job/ros2_batch_ci_linux/492/

**Comment by dirk-thomas** [comment]
The CI job has no effect since `ament_cpplint` is not enabled as a common linter.

**Comment by esteve** [comment]
But it failed, so running the CI job is always a good a idea. Anyway, I'll fix the compile errors.

**Comment by dirk-thomas** [comment]
I expected you to compile the code locally before creating the PRs. In order to run `ament_cpplint` in the CI it needs to be added to https://github.com/ament/ament_lint/blob/master/ament_lint_common/package.xml But several packages will have other cpplint errors until the pending items on https://github.com/ros2/ros2/issues/12 are addressed.

**Comment by esteve** [comment]
I expected it wouldn't fail, but mistakes happen.

**Comment by esteve** [comment]
Errors fixed and compiles locally.
