### ISSUE TITLE
[ament_cppcheck]  uninitialized variable problem

### ISSUE THREAD

**Issue by ClobotLucy** [ament/ament_lint#353]
I checked the cpp file via ament_cpp.

![Screenshot from 2022-01-26 16-29-57](https://user-images.githubusercontent.com/50474013/151121030-3e8a01bd-261b-434d-a4d5-8eceb8aeea08.png)

However, it is a member variable of the class, and I set the value.
I keep getting error:uninitvar contents.
How can I solve this?

**Comment by aprotyas** [comment]
ament_cppcheck invokes the cppcheck static analysis tools, so this question is out of scope for this repository.
As with most static analysis tools, and without further context, this could just be a false positive.

**Comment by clalancette** [comment]
Right, this looks like some kind of problem in the code, but it is hard to say.  In any case, I'll suggest asking questions like this on either https://stackoverflow.com, or on https://answers.ros.org.  I'm going to close this out.
