### ISSUE TITLE
Formatting with `ament_cpplint`

### ISSUE THREAD

**Issue by aalbaali** [ament/ament_lint#356]
Hi,

Is there a way to _format_ a C++ file with `ament_cpplint`?

I'm able to view the errors by running `ament_cpplint src/`, but so far I have to manually implement the changes. Furthermore, I'm wondering if there is a way to view the errors in VSCode or some other editor rather than manually running `ament_cpplint`.

Thanks

**Comment by aprotyas** [comment]
Hi @aalbaali, the ament tools basically just wrap around the actual linters, and in this case cpplint doesn't provide a format or in-place edit option, so I don't think this is possible.

Integrating what you want is pretty simple on the ament_lint side if it exists in cpplint though, so if you're really interested you can try to submit changes upstream?

Consider ament_uncrustify or ament_clang_format instead.

**Comment by aalbaali** [comment]
Thanks for replying promptly,

In this case I'll stick to ament_uncrustify since ament_clang_format might have [different style formatting](https://answers.ros.org/question/325019/is-there-a-clang-format-file-for-ros-2/?answer=325027#post-id-325027).

I'll close this issue for now and will reopen it if I push changes upstream.

Best
