### ISSUE TITLE
[ament_copyright] Copyright capitalization allowing uppercase

### ISSUE THREAD

**Issue by zflat** [ament/ament_lint#359]
I am using the approach described in https://answers.ros.org/question/343351/whats-the-proper-way-to-use-a-proprietary-software-license-according-to-ament_copyright/?answer=343355#post-id-343355 to add a proprietary license for my organization that can be enforced with `ament_copyright`.

One issue that I am running into is that the source files in my organization have all uppercase header text. However, the `parser.py` method `search_copyright_information` is strict about capitalization using the regex:

```python
pattern = r'^[^\n\r]?\s*(?:\\copyright\s*)?' \
              r'Copyright(?:\s+\(c\))?\s+(%s(?:,\s*%s)*),?\s+([^\n\r]+)$' % \
        (year_or_year_range, year_or_year_range)
```

Since I have source files with "COPYRIGHT" instead of "Copyright", the `search_copyright_information` does not find the copyright. Same for "(C)" instead of "(c)".

Which of these changes would be best?
* The `content` passed to the `search_copyright_information` be converted to lowercase and then the regex changed to assume lowercase? 
* Add an option for using `ament_copyright` in a case insensitive way? 
* Add the uppercase to the regex as a possible pattern to match against. If that is done then `"(C)"` would also be needed to match against.

**Comment by zflat** [comment]
@audrow @hidmic 
Could I please get a review of these pull requests that address issues I have been having with implementing a custom copyright check?
* https://github.com/ament/ament_lint/pull/358
* https://github.com/ament/ament_lint/pull/361
* https://github.com/ament/ament_lint/pull/363

**Comment by methylDragon** [comment]
Looks like this issue is now resolved with all the PRs merged? Let me know if there are still any issues, if not, do close the issue if everything's fine! :raised_hands: :tada:
