### ISSUE TITLE
[ament_flake8] Exclude directories / file patterns defined in config file are ignored 

### ISSUE THREAD

**Issue by danrauch** [ament/ament_lint#382]
Since commit a72d149eac6cebdcf6e47cf4a6feaf46ed7778d8 "exclude" parameters defined in the ament_flake8.ini file are ignored.

Steps to reproduce:

1. exclude a file in ament_flake8.ini via the exclude = "filename.py" parameter
2. introduce a flake8-relevant formatting error in the excluded file
3. run flake8 test (e.g. for a ros2 package)
4. observe test failure

**Comment by methylDragon** [comment]
I'll need to do some additional testing, but I suspect the CLI call that gets generated:

`flake8 ... --config=XXX --exclude=XXX` from #335 is causing any `exclude` directives in the config file to get overwritten.

There are three approaches I can see to resolve this:
1. Only use `extend-exclude` in the config file
2. Only use `extend-exclude` when appending to CLI args
3. Introduce logic to parse the config file, pull out `exclude` args, and extend the list sent to the CLI `exclude` arg instead.

**Comment by methylDragon** [comment]
(1) and (2) don't work.

We'll need to implement (3)

**Comment by methylDragon** [comment]
Fix here: https://github.com/ament/ament_lint/pull/387
