### ISSUE TITLE
add --update option for ament_copyright

### ISSUE THREAD

**Issue by tfoote** [ament/ament_lint#4]
Since the tool knows what should be there, it should be able to assist injecting the correct headers.

From: https://github.com/ament/ament_lint/pull/3#issuecomment-77659212

Make sure to use the canonical template from the discussion in #3

**Comment by dirk-thomas** [comment]
The ament_copyright package has been updated with the two referenced PRs.

Regarding the referenced "template": it also includes license information. I think we need a separate package dealing with that.
