### ISSUE TITLE
[ament_uncrustify] returns different result between galactic and humble

### ISSUE THREAD

**Issue by y-okumura-isp** [ament/ament_lint#402]
We have different results by ament_uncrustify between galactic and humble.

Here is the sample code:

```
// sample.hpp
#include <memory>

using ConstRefSharedConstPtr = const std::shared_ptr<const int>&;
```

We have no error on galactic, but not on humble. Here is the results:

On galactic:

```
# galactic
$ which ament_uncrustify
/opt/ros/galactic/bin/ament_uncrustify

$ ament_uncrustify sample.hpp
No code style divergence in file 'sample.hpp'

No problems found
```

On humble:

```
$ which ament_uncrustify
/opt/ros/humble/bin/ament_uncrustify

$ ament_uncrustify sample.hpp
Code style divergence in file 'sample.hpp':

--- sample.hpp
+++ sample.hpp.uncrustify
@@ -3 +3 @@
-using ConstRefSharedConstPtr = const std::shared_ptr<const int>&;
+using ConstRefSharedConstPtr = const std::shared_ptr<const int> &;

1 files with code style divergence
```

**Comment by clalancette** [comment]
Yes, during Humble we updated uncrustify to version 0.72, which has slightly different behavior.

There's not a whole lot we can do about this, so I'm going to close this out.  If you feel like this is in error, feel free to reopen.

**Comment by y-okumura-isp** [comment]
@clalancette 

Thank you for reply.

I wondered if there are some setting or work around to pass both LINT.
But it seems we need to update codes like in ros2/rclcpp#1884.
It is good to know the reason. Thank you very much.
