### ISSUE TITLE
Please tag a new release of `ament_lint` for `foxy`

### ISSUE THREAD

**Issue by esteve** [ament/ament_lint#434]
Because of the changes in `Pydocstyle` 6.2.0 (addressed in https://github.com/ament/ament_lint/pull/431), `foxy`'s latest tagged version of `ament_lint` makes tests fail.

`humble` and `rolling` already have tagged releases that incorporate this change, but unfortunately `foxy` doesn't and it's causing projects that use https://github.com/ros-tooling/setup-ros to fail their CI jobs, due to the latter updating `Pydocstyle` to the latest version during the `setup-ros` phase. Thanks!

**Comment by quarkytale** [comment]
So this seems to be taken care of in `0.9.8` (see https://github.com/ament/ament_lint/compare/0.9.7...0.9.8), closing it out!

**Comment by esteve** [comment]
@quarkytale Thanks!
