### ISSUE TITLE
What is the general release strategy?

### ISSUE THREAD

**Issue by ct2034** [ament/ament_lint#444]
I would be interested in a feature (https://github.com/ament/ament_lint/pull/386) to be available in humble. As far as I can tell, this is currently not the case, because only version 0.12.6 is released on humble. When can we expect another release in humble? And what is your general strategy towards that?

**Comment by clalancette** [comment]
The general strategy is to do all feature development on the development version, Rolling (the `rolling` branch).  From there, we can backport into the stable distributions if someone requests it, and it meets our criteria (basically it can't break API or ABI).

For that particular issue, it looks like it probably meets the criteria, so I'll ask the bot to do a backport of it.  It will then need to be reviewed, merged, and released like all other changes.

For now I'm going to close this one out.
