### ISSUE TITLE
ament_flake8 fails with flake8>=6.0.0

### ISSUE THREAD

**Issue by nwn** [ament/ament_lint#460]
After upgrading to flake8 version 6.0.0, we see the following error when running `ament_flake8`:

```
Traceback (most recent call last):
  File "/NIX/STORE/RKGSHK3W2KKRGX8CZ33F0GMR4YCM4I9H-ament_flake8/bin/ament_flake8", line 33, in <module>
    sys.exit(load_entry_point('ament-flake8==0.15.1', 'console_scripts', 'ament_flake8')())
  File "/NIX/STORE/RKGSHK3W2KKRGX8CZ33F0GMR4YCM4I9H-ament_flake8/lib/python3.10/site-packages/ament_flake8/main.py", line 31, in main
    rc, _ = main_with_errors(argv=argv)
  File "/NIX/STORE/RKGSHK3W2KKRGX8CZ33F0GMR4YCM4I9H-ament_flake8/lib/python3.10/site-packages/ament_flake8/main.py", line 88, in main_with_errors
    report = generate_flake8_report(
  File "/NIX/STORE/RKGSHK3W2KKRGX8CZ33F0GMR4YCM4I9H-ament_flake8/lib/python3.10/site-packages/ament_flake8/main.py", line 231, in generate_flake8_report
    opts, _ = parse_config_file(config_file)
  File "/NIX/STORE/RKGSHK3W2KKRGX8CZ33F0GMR4YCM4I9H-ament_flake8/lib/python3.10/site-packages/ament_flake8/main.py", line 199, in parse_config_file
    opts_manager = manager.OptionManager(
TypeError: OptionManager.__init__() missing 1 required keyword-only argument: 'formatter_names'
```

The problem comes from [this initializer](https://github.com/ament/ament_lint/blob/b4be064953c4154fd3bb6f804b04dc196c2666d2/ament_flake8/ament_flake8/main.py#L199-L203), which doesn't include the new [`formatter_names`](https://github.com/PyCQA/flake8/blob/6.0.0/src/flake8/options/manager.py#L216) parameter [added](https://github.com/PyCQA/flake8/commit/48b29191303b271a162b3acbdfba3e5cf310b50c#diff-286625233c22073bf3e0271e7e7158cd58438857a4c404d544d2b70970988353) in version 6.0.0. It shouldn't be too difficult to fix this in a version dependent way as is already done in that function. However, there may be more breakages that appear beyond this point.

For now, sticking with flake8 version 5.0.4 resolves the issue.

**Comment by abrzozowski** [comment]
Take a look at https://github.com/ament/ament_lint/pull/459

**Comment by clalancette** [comment]
Closing this since it was solved with #459

**Comment by Ryanf55** [comment]
When will this make it into humble binaries? This bug is preventing me from passing tests in `launch_ros`.
```
$ apt show ros-humble-ament-flake8
Package: ros-humble-ament-flake8
Version: 0.12.9-1jammy.20231117.163433
Priority: optional
Section: misc
Maintainer: Michael Jeronimo <michael.jeronimo@openrobotics.org>
Installed-Size: 62.5 kB
Depends: python3-flake8, ros-humble-ament-lint, ros-humble-ros-workspace
Download-Size: 15.4 kB
APT-Manual-Installed: no
APT-Sources: http://packages.ros.org/ros2/ubuntu jammy/main amd64 Packages
Description: The ability to check code for style and syntax conventions with flake8.
```

**Comment by abrzozowski** [comment]
@Ryanf55 Check the latest commit from the `humble` branch https://github.com/ament/ament_lint/commits/humble/

The change is already there, but it's not tagged. So, it's probably not released, but I don't know how often releases are performed.

**Comment by Ryanf55** [comment]
> @Ryanf55 Check the latest commit from the `humble` branch https://github.com/ament/ament_lint/commits/humble/
> 
> The change is already there, but it's not tagged. So, it's probably not released, but I don't know how often releases are performed.

Yep. I tried spinning the release myself but hit problems with bloom. Hopefully a maintainer can make a release soon.
