### ISSUE TITLE
xmllint Requires member_of_group to be before export

### ISSUE THREAD

**Issue by erichlf** [ament/ament_lint#496]
When I run `xmllint` with my `packages.xml` having the following order
```xml
  <export>
    <build_type>ament_cmake</build_type>
  </export>

  <member_of_group>rosidl_interface_packages</member_of_group>
```
 I get the following error
> package.xml:31: element member_of_group: Schemas validity error : Element 'member_of_group': This element is not expected.

However, simply changing things to the following
```xml
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
```
causes this to go away. Is it intended that the order matters here?

**Comment by christophebedard** [comment]
I believe the order matters, yes. Same for the order of `<version>`/`<description>`/`<maintainer>`/`<license>`/etc. See the schema: http://download.ros.org/schema/package_format3.xsd

**Comment by erichlf** [comment]
Yep looks like it does matter.

**Comment by gavanderhoorn** [comment]
@christophebedard: order matters because it seems the XSD uses a `xs:sequence` for the `package` element description.

But it's not clear to me *why*.

**Comment by christophebedard** [comment]
Consistency, probably?

**Comment by gavanderhoorn** [comment]
I've looked through the [history of the files](https://github.com/ros-infrastructure/rep/tree/f87e1dbc177d5e116a35898a05c870b11b7bab88/xsd), but can't really find any comments on this. Dirk appears to 'just' commit the `.xsd`s, and that's that.

**Comment by christophebedard** [comment]
Yeah, and the REPs (149 for format 3 or 140 for format 2) don't seem to explicitly mention that the elements have a specific order either.

I know that it is generally accepted -- or, rather, known -- that `<maintainer>` goes before `<license>`, which goes before `<author>`, but I've never seen any rationale for it.

**Comment by gavanderhoorn** [comment]
I remembered the original discussion on `ros-users` that was the start of the schemas: [[ros-users] review: catkin documentation review for package.xml format 2](http://lists.ros.org/lurker/message/20140518.162055.0724f54c.en.html), but there's also no mention of any explicit order there.

Perhaps the original author just used `sequence` and it was never really discussed.

> I know that it is generally accepted -- or, rather, known -- that `<maintainer>` goes before `<license>`, which goes before `<author>` (otherwise the linter complains), but I've never seen any rationale for it.

I do believe that's mostly just convention.

**Comment by fujitatomoya** [comment]
@erichlf 

we have talked about this a bit in today's ROS 2 team meeting. this is more like a question not an issue, besides this is how this works atm, and currently no plan to change the behavior. so if that is okay, we can close this for now.

if we escalate this as an issue, feel free to open this to track.
