### ISSUE TITLE
Requesting permissions to create a branch

### ISSUE THREAD

**Issue by ivanperez-keera** [ament/ament_lint#506]
Hi,

I'm one of the maintainers of Space ROS, which currently has a dedicated branch `spaceros` in this repo.

I'd like to have permissions to create another branch `spaceros-main` which will become our main development branch.

Tagging @tfoote and @clalancette .

Thanks!

**Comment by clalancette** [comment]
So I'm not comfortable giving you permissions here; that is supposed to be reserved for ROS PMC members.

I could go ahead and create the branch for you, but it brings up a separate concern.  If you want to be able to have administrative capabilities like this, and SpaceROS is essentially a fork of ROS 2, would it make more sense for SpaceROS to switch to a fork of `ament_lint` here?  Pinging @gbiggs for thoughts here as well.

**Comment by ivanperez-keera** [comment]
If it helps, the long-term plan is to merge our changes into the main `ament_lint`, if possible, so that we don't have to keep maintaining our separate branch.

**Comment by ivanperez-keera** [comment]
As for the current plan, I'm happy having a branch `spaceros_main`. That will solve our concern. Thanks!

**Comment by clalancette** [comment]
All right, I've now created a `spaceros_main` branch here, so closing this out.

**Comment by ivanperez-keera** [comment]
Thanks!
