### ISSUE TITLE
ament_copyright failing to detect copyright with multi-copyright

### ISSUE THREAD

**Issue by Theosakamg** [ament/ament_lint#65]
If the licence contains:
```
// Copyright 2015 A Corporation.
// Copyright 2016 B Corporation.
```

Testing result :
`my_file.h: copyright=<unknown> (2016), license=<unknown>`

**Comment by dirk-thomas** [comment]
Until now we haven't had this use case yet. It would be great if you could consider to create a PR for supporting this.

**Comment by dirk-thomas** [comment]
Please see #66. It should support your use case. If you could give it a try and comment here if it works for you that would be great.

**Comment by Theosakamg** [comment]
Perfect ! :+1:
