### ISSUE TITLE
IWYU not in sync

### ISSUE THREAD

**Issue by Karsten1987** [ament/ament_lint#68]
I recently ran into an issue of the cpplint which was merged upstream but doesn't seem to be merged in our repo.
https://github.com/google/styleguide/pull/158/files

**Comment by dirk-thomas** [comment]
It looks to me that our version of the file already contains the patch of the referenced PR: https://github.com/ament/ament_lint/blob/d079913a7fb42016832924787c56a6435950437a/ament_cpplint/ament_cpplint/cpplint.py#L5512-L5518

**Comment by Karsten1987** [comment]
Must have overlooked that. Sorry for the noise then.
