### ISSUE TITLE
cpplint error when .git directory not present

### ISSUE THREAD

**Issue by sagniknitr** [ament/ament_lint#92]
On deleting the .git directory the repo, running cpplint will show 
`  "#ifndef header guard has wrong style, please use: XXXX_XXX_AB...." `
 for any header file.
Is this a bug with cpplint or any ament tool ? Can it be fixed ?

Thanks!!

**Comment by dirk-thomas** [comment]
Your header files need to be either in a directory (or subdirectory) with a "common" name (`incude`, `src`, `test`, see https://github.com/ament/ament_lint/blob/391089687a0b6dc511a13aee4a104e8a7274aa9f/ament_cpplint/ament_cpplint/main.py#L232) or the root of the repository can be identified (`.git`, `.hg`, `.svn`, see https://github.com/ament/ament_lint/blob/391089687a0b6dc511a13aee4a104e8a7274aa9f/ament_cpplint/ament_cpplint/main.py#L252). If neither of the two conditions is true it is unclear what to pass as `--root` to `cpplint` to derive the "correct" header guard from.

**Comment by sagniknitr** [comment]
@dirk-thomas ok.Got it.

**Comment by sagniknitr** [comment]
Just a experiment I tried..... I removed the .git folder from the rcl package in the ros 2 ardent release source code...After that when I run ament test for cpplint  I receive the following cpplint errors. 

` /home/sagnik/Work/ROS/ros2_ardent_alvacore/install/bin/ament_cpplint --xunit-file /home/sagnik/Work/ROS/ros2_ardent_alvacore/build/rcl/test_results/rcl/cpplint.xunit.xml
3: /home/sagnik/Work/ROS/ros2_ardent_alvacore/src/ros2/rcl/rcl/include/rcl/allocator.h:15:  #ifndef header guard has wrong style, please use: __HOME__SAGNIK__WORK__ROS__ROS2_ARDENT_ALVACORE__SRC__ROS2__RCL__RCL__INCLUDE__RCL__ALLOCATOR_H_  [build/header_guard] [5]
'

and the final result comes as 
` 	  3 - cpplint (Failed)'
`Errors while running CTest`

It seems that the cpplint test will exclusively look for the .git folder at the root of the package.

**Comment by dirk-thomas** [comment]
Thank you for pointing this out. Looking at the logic to determine the root it really seems broken to me. Please see # for a patch. It would be great if you could give it a try and confirm if resolves the problem for you.

**Comment by sagniknitr** [comment]
@dirk-thomas Initial testing with the patch is working fine.The Cpplint errors are gone now.
Thank you for the patch.

**Comment by dirk-thomas** [comment]
Thank you for trying the patch and reporting back.
